<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employees.proto

namespace GPBMetadata;

class Employees
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
j
employees.proto"$
Employee

id (
name (	")
	Employees
	employees (2	.Employeebproto3'
        , true);

        static::$is_initialized = true;
    }
}

