# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
# Generated protocol buffer code for book.proto


library("R6")


# R class for Book message
Book <- R6Class("Book",
  public = list(
    isbn = NULL,
    title = NULL,
    author = NULL
  )
)
# R class for GetBookRequest message
GetBookRequest <- R6Class("GetBookRequest",
  public = list(
    isbn = NULL
  )
)
# R class for GetBookViaAuthor message
GetBookViaAuthor <- R6Class("GetBookViaAuthor",
  public = list(
    author = NULL
  )
)
# R class for BookStore message
BookStore <- R6Class("BookStore",
  public = list(
    name = NULL,
    books = list()
  )
)
