# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employees.proto
# Generated protocol buffer code for employees.proto


library("R6")


# R class for Employee message
Employee <- R6Class("Employee",
  public = list(
    id = NULL,
    name = NULL
  )
)
# R class for Employees message
Employees <- R6Class("Employees",
  public = list(
    employees = list()
  )
)
