# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto
# Generated protocol buffer code for greeter.proto


library("R6")


# R class for SayHelloRequest message
SayHelloRequest <- R6Class("SayHelloRequest",
  public = list(
    name = NULL
  )
)
# R class for SayHelloResponse message
SayHelloResponse <- R6Class("SayHelloResponse",
  public = list(
    message = NULL
  )
)
